name: CI ITI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the code
        uses: actions/checkout@v3

      - name: Install python "version 3.10"
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Run pip install flask pytest
        run: pip install flask pytest

      - name: Run pytest test_app.py -v
        run: pytest test_app.py -v